# Generated by Django 5.0.2 on 2024-04-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'offre'), (1, 'demande')], default=0)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contactInfo', models.CharField(max_length=255)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('texte', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('typeStg', models.IntegerField(choices=[(1, 'ouvrier'), (2, 'technicien'), (3, 'PFE')], default=1)),
                ('societe', models.CharField(max_length=100)),
                ('duree', models.IntegerField(default=0)),
                ('sujet', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('heuredep', models.DateTimeField(auto_now_add=True)),
                ('nbreSiege', models.IntegerField()),
                ('contactInfo', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('like', models.BooleanField(default=False)),
                ('poste', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='StudentHelp.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='StudentHelp.user')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.user'),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.evenement')),
                ('club', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.evenement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.evenement')),
                ('prix', models.FloatField()),
            ],
            bases=('StudentHelp.evenement',),
        ),
    ]
