# Generated by Django 5.0.2 on 2024-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0005_alter_user_options_user_password_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
