# Generated by Django 5.0.2 on 2024-05-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0007_remove_reaction_comment_remove_reaction_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.reaction')),
                ('com', models.CharField(max_length=100, null=True)),
            ],
            bases=('StudentHelp.reaction',),
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.reaction')),
                ('li', models.BooleanField(default=False, null=True)),
            ],
            bases=('StudentHelp.reaction',),
        ),
    ]
