# Generated by Django 5.0.2 on 2024-05-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0008_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='reaction_ptr',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
