# Generated by Django 5.0.2 on 2024-05-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0009_remove_like_reaction_ptr_delete_comment_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
