# Generated by Django 5.0.2 on 2024-05-06 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0010_delete_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=100, null=True)),
                ('poste', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='StudentHelp.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='StudentHelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li', models.BooleanField(default=False, null=True)),
                ('poste', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='StudentHelp.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='StudentHelp.user')),
            ],
        ),
    ]
